# Generated by Django 3.2.25 on 2024-04-15 04:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='prod_col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('prod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Name of product', max_length=255)),
                ('sku_number', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_app.categoryofproducts')),
                ('color_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_app.prod_col')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDepotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('address', models.CharField(help_text='enter your address here', max_length=255, null=True)),
                ('store_email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('contacts', models.IntegerField(max_length=255)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('Country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_app.country_code')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_app.productdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDEpartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_app.productdetails')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_app.storedepotmodel')),
            ],
        ),
    ]
