# Generated by Django 3.2.25 on 2024-04-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0004_auto_20240416_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedepotmodel',
            name='Country_code',
            field=models.CharField(max_length=3),
        ),
    ]
