# Generated by Django 3.2.25 on 2024-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0005_alter_storedepotmodel_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydepartmentmodel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
