# Generated by Django 3.2.25 on 2024-04-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0007_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pro_app.categoryofproducts'),
        ),
    ]
