# Generated by Django 3.2.25 on 2024-04-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0008_orderitems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='category',
        ),
    ]
