# Generated by Django 3.2.25 on 2024-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0009_remove_orderitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='sku_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
